### ISSUE TITLE
Howdy

### ISSUE THREAD

**Issue by Xaezareon** [cyanraccoon/cyanraccoon.github.io#1]
https://user-images.githubusercontent.com/41632382/216249266-73965362-3fc8-4aae-8d9b-d0902c74c1a6.mp4

**Comment by Xaezareon** [comment]
Update: Upon further review of your code, i have come to the conclusion that

![❓](https://user-images.githubusercontent.com/41632382/216249664-2ebe2585-4f07-44af-8424-1c227a7c74b8.gif)

**Comment by cyanraccoon** [comment]
u sussy baka

**Comment by Xaezareon** [comment]
dont call me that u nerd 

https://user-images.githubusercontent.com/41632382/216250769-825cf58c-1fef-41fd-bf27-481efdf5fd09.mp4
